### ISSUE TITLE
does not work for new file

### ISSUE THREAD

**Issue by nn1900** [b4winckler/vim-objc#3]
When I use "vim filename.m" to create a new file for edit, there's no syntax color highlighting. It only works for editing existing file. I have also tried c/c++ source files, and that worked fine for me. Is this a bug or?

my vimrc file looks as below:

execute pathogen#infect()
set nocompatible
filetype on
filetype plugin indent on
syntax on

" tab space settings
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set number

**Comment by keith** [comment]
Is vim correctly detecting `*.m` files as Objective-C? What's the output of `set ft`? You may need to add something like:

```
autocmd BufNewFile,BufRead *.h,*.m,*.pch setlocal filetype=objc
```

To your vimrc

**Comment by nn1900** [comment]
@Keithbsmiley that works for me. thanks a lot.

**Comment by b4winckler** [comment]
Yeah, I think Vim defaults to associating `.m` files with Matlab...
